"""agregar ultimo_checkin

Revision ID: 13ad46169868
Revises: 7b6ad840da80
Create Date: 2026-05-15 08:36:13.529513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ad46169868'
down_revision = '7b6ad840da80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_checkin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('ultimo_checkin')

    # ### end Alembic commands ###
