"""tabla metricas

Revision ID: 25fe520728e5
Revises: b3ec15f39c08
Create Date: 2026-05-21 11:19:08.928595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fe520728e5'
down_revision = 'b3ec15f39c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('ram', sa.Float(), nullable=True),
    sa.Column('disco', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas')
    # ### end Alembic commands ###
