"""agregar metricas equipo

Revision ID: b3ec15f39c08
Revises: 13ad46169868
Create Date: 2026-05-16 16:21:21.663184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ec15f39c08'
down_revision = '13ad46169868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ram_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disco_actual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_column('disco_actual')
        batch_op.drop_column('ram_actual')
        batch_op.drop_column('cpu_actual')

    # ### end Alembic commands ###
